### ISSUE TITLE
Please answer

### ISSUE THREAD

**Issue by dongpu1813** [Wildfire-new/Wildfire-MN-POW#1]
ann 
algo
addnode
![image](https://user-images.githubusercontent.com/42663880/100688963-7edabf80-33be-11eb-9edf-2cef864a2a9c.png)
![image](https://user-images.githubusercontent.com/42663880/100689401-5c957180-33bf-11eb-82da-892b7e8ec50d.png)

**Comment by Wildfire-new** [comment]
Algo x11 POW/MN
addnode =161.97.122.124:25572
addnode=86.57.193.186:25572
addnode=144.91.90.160:25572
