### ISSUE TITLE
Kindly bump version

### ISSUE THREAD

**Issue by laakie** [Wildfire-new/Wildfire-MN-POW#7]
Wallet getinfo still returns "version": 1000000,

Please update to reflect version 1.1.1.1

**Comment by Wildfire-new** [comment]
https://www.github.com/Wildfire-new/Wildfire-MN-POW/tree/1.1.1.1.1/configure.ac

Pls check, !!

**Comment by Wildfire-new** [comment]
I think you compiled the old one?

**Comment by laakie** [comment]
I've compiled from git checkout tags/v1.1.1.1 as well as the ZIP file from the releases

Both the same result.
Not sure what's the problem then ?

**Comment by Wildfire-new** [comment]
that's weird, i just tried it he shows me the right version.


  | {   "version": 1010101,   "protocolversion": 70215,   "walletversion": 61000,   "balance": 1078753.33033945,   "privatesend_balance": 0.00000000,   "blocks": 22095,   "timeoffset": 1,   "connections": 9,   "proxy": "",   "difficulty": 43322.89417674531,   "testnet": false,   "keypoololdest": 1606815864,   "keypoolsize": 999,   "unlocked_until": 146028896743,   "paytxfee": 0.00000000,   "relayfee": 0.00001000,   "errors": "" }
-- | --
